---
title: "Chinese names in US Babynames"
author: "Hao"
date: "4/18/2019"
output: html_document
---

```{r, message=F, warning=F}
library(babynames)
library(tidyverse)
library(sparkline)
knitr::opts_chunk$set(message = F, warning = F)
```

```{r}
sparkline(0)
```

```{r}
sample_hanzi <- read_csv("sample_hanzi.csv")

pinyin_1_word <- sample_hanzi$pinyin
pinyin_2_words <- combn(sample_hanzi$pinyin, 2) %>%
  apply(2, paste0, collapse = "")
pinyin_first_names <- c(pinyin_1_word, pinyin_2_words)

hanzi_1_word <- sample_hanzi$hanzi
hanzi_2_words <- combn(sample_hanzi$hanzi, 2) %>%
  apply(2, paste0, collapse = "")
hanzi_first_names <- c(hanzi_1_word, hanzi_2_words)

first_names <- tibble(
  pinyin = pinyin_first_names,
  hanzi = hanzi_first_names
)
chinese_babynames <- babynames %>%
  mutate(lowername = tolower(name)) %>%
  inner_join(first_names, by = c("lowername" = "pinyin")) %>%
  mutate(name = paste(name, hanzi, sep = " - ")) %>%
  select(-lowername, -hanzi)
```

# For Boys
```{r}
chinese_boys <- chinese_babynames %>%
  filter(sex == "M") %>%
  mutate(year = factor(year, 1880:2017)) %>%
  arrange(name) %>%
  select(-sex, -prop) %>%
  spread(year, n, fill = 0) %>%
  gather(year, n, -name) %>%
  group_nest(name) %>%
  mutate(n = map(data, ~sum(.x$n)),
         data = map(data, ~spk_chr(.x$n))) %>%
  unnest() %>%
  arrange(desc(n))

library(kableExtra)
kable(chinese_boys, escape = F) %>%
  kable_styling(full_width = F) 
```
